version: '3.8'
volumes:
  postgres_data:
  static:

services:
  db:
    image: postgres:12.4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  web:
    image: iodkoav/interviews:v02
    restart: always
    env_file:
      - ./.env
    volumes:
      - static:/static
    depends_on:
      - db
    expose:
      - "8000"
    entrypoint: ["bash", "entrypoint.sh"]
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:8000"
  nginx:
    image: nginx:1.21.1
    volumes:
      - static:/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
    ports:
      - "80:80"